[travis] update homebrew on macos
Otherwise build breaks on travis due to:
  Error: Your Homebrew is outdated. Please run `brew update`.
  Error: Kernel.exit